/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dev.CodeRulers.display;

import dev.CodeRulers.game.CodeRulers;
import java.awt.Image;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author seanz
 */
public class Display extends JFrame {
    //this is the logo for the game
    private ImageIcon logo;
    private JPanel panel1;
    //Jframe variables:
    private String title; //title of the jframe
    private int width,height; //width and height of jframe
    

    
    /**
     * The Constructor for the Display Class. In this block of code, all graphical
     * components of the game are initialized.
     */
    public Display(String title, String imageLogo, CodeRulers r) {

        
        System.out.println("Display Initialized.");
        logo = new ImageIcon(getClass().getResource("/resources/logo/" + imageLogo));
		
        initComponents();
        panel1 = new Panel(r);
	this.add(panel1);
        this.setIconImage(logo.getImage());
        this.setTitle(title);
        this.pack();
        this.setVisible(true);
    }
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(new java.awt.GridLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
